import { ExtensibleError } from "./extensible-error.ts";

export class InvalidError extends ExtensibleError {}
export class UnauthorizedError extends ExtensibleError {}
export class UnknowError extends ExtensibleError {}
export class NotImplementError extends ExtensibleError {}
export class AssertionError extends ExtensibleError {}
export class NotSupportError extends ExtensibleError {}

export class InvalidArgumentError extends ExtensibleError {}
export class InvalidStateError extends ExtensibleError {}
export class InvalidActionError extends ExtensibleError {}
export class InvalidTypeError extends ExtensibleError {}
export class InvalidValueError extends ExtensibleError {}
export class InvalidOperationError extends ExtensibleError {}
export class InvalidFormatError extends ExtensibleError {}
export class InvalidEncodingError extends ExtensibleError {}
export class InvalidFieldError extends ExtensibleError {}
export class InvalidRequestError extends ExtensibleError {}
export class InvalidResponseError extends ExtensibleError {}
export class InvalidMessageError extends ExtensibleError {}
export class InvalidHeaderError extends ExtensibleError {}
export class InvalidPayloadError extends ExtensibleError {}
export class InvalidURLError extends ExtensibleError {}
export class InvalidURISchemeError extends ExtensibleError {}
export class InvalidHostError extends ExtensibleError {}
export class InvalidPortError extends ExtensibleError {}

export class InvalidCharacterError extends ExtensibleError {}
export class InvalidIdentifierError extends ExtensibleError {}
export class InvalidNameError extends ExtensibleError {}
export class InvalidVersionError extends ExtensibleError {}
export class InvalidSizeError extends ExtensibleError {}
export class InvalidLengthError extends ExtensibleError {}
export class InvalidCountError extends ExtensibleError {}
export class InvalidIndexError extends ExtensibleError {}
export class InvalidRangeError extends ExtensibleError {}
export class InvalidRangeSizeError extends ExtensibleError {}
export class InvalidRangeUnitError extends ExtensibleError {}
export class InvalidPositionError extends ExtensibleError {}
export class InvalidOffsetError extends ExtensibleError {}
export class InvalidLimitError extends ExtensibleError {}
export class InvalidPageError extends ExtensibleError {}
export class InvalidPageCountError extends ExtensibleError {}

export class InvalidEmailError extends ExtensibleError {}
export class InvalidUsernameError extends ExtensibleError {}
export class InvalidPasswordError extends ExtensibleError {}
export class InvalidTokenError extends ExtensibleError {}
