export class InvalidError extends Error {}
export class UnauthorizedError extends Error {}
export class UnknowError extends Error {}
export class NotImplementError extends Error {}
export class AssertionError extends Error {}
export class NotSupportError extends Error {}

export class InvalidArgumentError extends Error {}
export class InvalidStateError extends Error {}
export class InvalidActionError extends Error {}
export class InvalidTypeError extends Error {}
export class InvalidValueError extends Error {}
export class InvalidOperationError extends Error {}
export class InvalidFormatError extends Error {}
export class InvalidEncodingError extends Error {}
export class InvalidFieldError extends Error {}
export class InvalidRequestError extends Error {}
export class InvalidResponseError extends Error {}
export class InvalidMessageError extends Error {}
export class InvalidHeaderError extends Error {}
export class InvalidPayloadError extends Error {}
export class InvalidURLError extends Error {}
export class InvalidURISchemeError extends Error {}
export class InvalidHostError extends Error {}
export class InvalidPortError extends Error {}

export class InvalidCharacterError extends Error {}
export class InvalidIdentifierError extends Error {}
export class InvalidNameError extends Error {}
export class InvalidVersionError extends Error {}
export class InvalidSizeError extends Error {}
export class InvalidLengthError extends Error {}
export class InvalidCountError extends Error {}
export class InvalidIndexError extends Error {}
export class InvalidRangeError extends Error {}
export class InvalidRangeSizeError extends Error {}
export class InvalidRangeUnitError extends Error {}
export class InvalidPositionError extends Error {}
export class InvalidOffsetError extends Error {}
export class InvalidLimitError extends Error {}
export class InvalidPageError extends Error {}
export class InvalidPageCountError extends Error {}

export class InvalidEmailError extends Error {}
export class InvalidUsernameError extends Error {}
export class InvalidPasswordError extends Error {}
export class InvalidTokenError extends Error {}
